.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..

.TH i3lock 1 "JANUARY 2012" Linux "User Manuals"

.SH NAME
i3lock \- improved screen locker

.SH SYNOPSIS
.B i3lock
.RB [\|\-v\|]
.RB [\|\-n\|]
.RB [\|\-b\|]
.RB [\|\-d\|]
.RB [\|\-i
.IR image.png \|]
.RB [\|\-c
.IR color \|]
.RB [\|\-t\|]
.RB [\|\-p
.IR pointer\|]
.RB [\|\-u\|]

.SH DESCRIPTION
.B i3lock
is a simple screen locker like slock. After starting it, you will see a white
screen (you can configure the color/an image). You can return to your screen by
entering your password.

.SH IMPROVEMENTS

.TP
* i3lock forks, so you can combine it with an alias to suspend to RAM (run "i3lock && echo mem > /sys/power/state" to get a locked screen after waking up your computer from suspend to RAM)

.TP
* You can specify either a background color or a PNG image which will be displayed while your screen is locked.

.TP
* You can specify whether i3lock should bell upon a wrong password.

.TP
* i3lock uses PAM and therefore is compatible with LDAP etc.


.SH OPTIONS
.TP
.B \-v, \-\-version
Display the version of your
.B i3lock

.TP
.B \-n, \-\-nofork
Don't fork after starting.

.TP
.B \-b, \-\-beep
Enable beeping. Be sure to not do this when you are about to annoy other people,
like when opening your laptop in a boring lecture.

.TP
.B \-d, \-\-dpms
Enable turning off your screen using DPMS. Note that, when you do not specify this
option, DPMS will turn off your screen after 15 minutes of inactivity anyways (if
you did not disable this in your X server).

.TP
.B \-u, \-\-no-unlock-indicator
Disables the unlock indicator. i3lock will by default show an unlock indicator
after pressing keys. This will give feedback for every keypress and it will
show you the current PAM state (whether your password is currently being
verified or whether it is wrong).

.TP
.BI \-i\  path \fR,\ \fB\-\-image= path
Display the given PNG image instead of a blank screen.

.TP
.BI \-c\  rrggbb \fR,\ \fB\-\-color= rrggbb
Turns the screen into the given color instead of white. Color must be given in 6-byte
format: rrggbb (i.e. ff0000 is red)

.TP
.B \-t, \-\-tiling
If an image is specified (via \-i) it will display the image tiled all over the screen
(if it is a multi-monitor setup, the image is visible on all screens).

.TP
.BI \-p\  win|default \fR,\ \fB\-\-pointer= win|default
If you specify "default",
.B i3lock
does not hide your Mousepointer. If you specify "win",
.B i3lock
displays a hardcoded Windows-Pointer (thus enabling you to fuck with your
friends by using a Screenshot of a Windows-Desktop as a locking-screen).

.SH SEE ALSO
.IR xautolock(1)
\- use i3lock as your screen saver

.SH AUTHOR
Michael Stapelberg <michael+i3lock at stapelberg dot de>

Jan-Erik Rediger <badboy at archlinux.us>
