.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..

.TH i3lock-color 1 "JANUARY 2012" Linux "User Manuals"

.SH NAME
i3lock-color \- improved screen locker

.SH SYNOPSIS
.B i3lock
.RB [\|\-v\|]
.RB [\|\-n\|]
.RB [\|\-b\|]
.RB [\|\-i
.IR image.png \|]
.RB [\|\-c
.IR color \|]
.RB [\|\-t\|]
.RB [\|\-p
.IR pointer\|]
.RB [\|\-u\|]
.RB [\|\-e\|]
.RB [\|\-f\|]

.SH DESCRIPTION
.B i3lock-color
is a simple screen locker like slock. After starting it, you will see a white
screen (you can configure the color/an image). You can return to your screen by
entering your password.

.SH IMPROVEMENTS

.IP \[bu] 2
i3lock forks, so you can combine it with an alias to suspend to RAM (run "i3lock && echo mem > /sys/power/state" to get a locked screen after waking up your computer from suspend to RAM)
.IP \[bu]
You can specify either a background color or a PNG image which will be displayed while your screen is locked.
.IP \[bu]
You can specify whether i3lock should bell upon a wrong password.
.IP \[bu]
i3lock uses PAM and therefore is compatible with LDAP, etc.


.SH OPTIONS
.TP
.B \-v, \-\-version
Display the version of your
.B i3lock

.TP
.B \-n, \-\-nofork
Don't fork after starting.

.TP
.B \-b, \-\-beep
Enable beeping. Be sure to not do this when you are about to annoy other people,
like when opening your laptop in a boring lecture.

.TP
.B \-u, \-\-no-unlock-indicator
Disable the unlock indicator. i3lock will by default show an unlock indicator
after pressing keys. This will give feedback for every keypress and it will
show you the current PAM state (whether your password is currently being
verified or whether it is wrong).

.TP
.BI \-i\  path \fR,\ \fB\-\-image= path
Display the given PNG image instead of a blank screen.

.TP
.BI \-c\  rrggbb \fR,\ \fB\-\-color= rrggbb
Turn the screen into the given color instead of white. Color must be given in 3-byte
format: rrggbb (i.e. ff0000 is red).

.TP
.B \-t, \-\-tiling
If an image is specified (via \-i) it will display the image tiled all over the screen
(if it is a multi-monitor setup, the image is visible on all screens).

.TP
.BI \-p\  win|default \fR,\ \fB\-\-pointer= win|default
If you specify "default",
.B i3lock
does not hide your mouse pointer. If you specify "win",
.B i3lock
displays a hardcoded Windows-Pointer (thus enabling you to mess with your
friends by using a screenshot of a Windows desktop as a locking-screen).

.TP
.B \-e, \-\-ignore-empty-password
When an empty password is provided by the user, do not validate
it. Without this option, the empty password will be provided to PAM
and, if invalid, the user will have to wait a few seconds before
another try. This can be useful if the XF86ScreenSaver key is used to
put a laptop to sleep and bounce on resume or if you happen to wake up
your computer with the enter key.

.TP
.B \-f, \-\-show-failed-attempts
Show the number of failed attempts, if any.

.TP
.B \-\-debug
Enables debug logging.
Note, that this will log the password used for authentication to stdout.

.SH i3lock-color options
.TP
.B \-S=number, \-\-screen=number
Specifies which display to draw the unlock indicator and clock on. By default, they'll be placed on every screen.
Note that this number is zero indexed. The ordering is dependent on libxinerama.

.TP
.B \-B=sigma, \-\-blur=sigma
Captures the screen and blurs it using the given sigma (radius).
Images may still be overlaid over the blurred screenshot.

.TP
.B \-\-indicator
Forces the indicator to always be visible, instead of only showing on activity.

.TP
.B \-\-composite
Some compositors have problems with i3lock trying to render over them, so this argument is disabled by default. However, some will work properly with it, so it's been left enabled.

.TP
.B \-\-insidevercolor=rrggbbaa
Sets the interior circle color while the password is being verified.

.TP
.B \-\-insidewrongcolor=rrggbbaa
Sets the interior circle color for during flash for an incorrect password.

.TP
.B \-\-insidecolor=rrggbbaa
Sets the default "resting" color for the interior circle.

.TP
.B \-\-ringvercolor=rrggbbaa
Sets the ring color while the password is being verified.

.TP
.B \-\-ringwrongcolor=rrggbbaa
Sets the ring color during the flash for an incorrect password.

.TP
.B \-\-ringcolor=rrggbbaa
Sets the default ring color.

.TP
.B \-\-linecolor=rrggbbaa
Sets the color for the line separating the inside circle, and the outer ring.

.TP
.B \-\-line\-uses\-ring
Conflicts with \-\-line\-uses\-inside. Overrides \-\-linecolor. The line will match the ring color.

.TP
.B \-\-line\-uses\-inside
Conflicts with \-\-line\-uses\-ring. Overrides \-\-linecolor; the line will match the inside color.

.TP
.B \-\-keyhlcolor=rrggbbaa
Sets the color of the ring 'highlight' strokes that appear upon keypress.

.TP
.B \-\-bshlcolor=rrggbbaa
Sets the color of the ring 'highlight' strokes that appear upon backspace.

.TP
.B \-\-separatorcolor=rrggbbaa
Sets the color of the 'separtor', which is at both ends of the ring highlights.

.TP
.B \-\-textcolor=rrggbbaa
Sets the color of the status text ("verifying...", "wrong!", etc).

.TP
.B \-\-timecolor=rrggbbaa
Sets the color of the time in the clock.

.TP
.B \-\-timestr="%H:%M:%S"
Sets the format used for generating the time string. See strftime(3) for a full list of format specifiers.

.TP
.B \-\-timefont=sans-serif
Sets the font used to render the time string.

.TP
.B \-\-timesize=number
Sets the font size for rendering the time string. Defaults to 32.

.TP
.B \-\-timepos="x position:y position"
Sets the position for the time string. Valid variables include:

.RS
.RS
x - x position of the current display. Corresponds to the leftmost row of pixels on that display.

y - y position of the current display. Corresponds to the topmost row of pixels on that display.

w - width of the current display.

h - height of the current display.

ix - the x value of the indicator on the current display.

iy - the y value of the indicator on the current display.

cw - the clock width.

ch - the clock height.

.RE
.RE

.TP
.B \-\-datecolor=rrggbbaa
Sets the color of the date in the clock.

.TP
.B \-\-datestr="%A, %m %Y
Sets the format used for generating the date string. See strftime(3) for a full list of format specifiers.
.TP
.B \-\-datefont=sans-serif
Sets the font used to render the date string.

.TP
.B \-\-datesize=number
Sets the font size for rendering the date string. Defaults to 14.

.TP
.B \-\-datepos="x position:y position"
Sets the position for the date string. All the variables from \-\-timepos may be used, in addition to:

.RS
.RS
tx - the computed x value of the timestring, for the current display.

ty - the computed y value of the timestring, for the current display.

.RE
.RE

.TP
.B \-\-refresh\-rate=seconds
The refresh rate of the indicator, given in seconds. This should automatically align itself, but is somewhat buggy currently.

.TP
.B \-\-veriftext="text"
Sets the string to be shown while verifying the password/input/key/etc. Defaults to "verifying…".

.TP
.B \-\-wrongtext="text"
Sets the string to be shown upon entering an incorrect password. Defaults to "wrong!".

.TP
.B \-\-textsize=number
The fontsize of the status text. Defaults to 28.

.TP
.B \-\-modsize=number
The fontsize of the text listing all the active modifiers (caps lock, num lock, etc). Defaults to 14.

.TP
.B \-\-radius
The radius of the circle. Defaults to 90.

.SH DPMS

The \-d (\-\-dpms) option was removed from i3lock in version 2.8. There were
plenty of use-cases that were not properly addressed, and plenty of bugs
surrounding that feature. While features are not normally removed from i3 and
its tools, we felt the need to make an exception in this case.

Users who wish to explicitly enable DPMS only when their screen is locked can
use a wrapper script around i3lock like the following:

.Vb 6
\&	#!/bin/sh
\&	revert() {
\&	  xset dpms 0 0 0
\&	}
\&	trap revert HUP INT TERM
\&	xset +dpms dpms 5 5 5
\&	i3lock -n
\&	revert
.Ve

The \-I (-\-inactivity-timeout=seconds) was removed because it only makes sense with DPMS.

.SH SEE ALSO
.IR xautolock(1)
\- use i3lock as your screen saver

.SH AUTHOR
Michael Stapelberg <michael+i3lock at stapelberg dot de>

Jan-Erik Rediger <badboy at archlinux.us>
