.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..

.TH i3lock 1 "JANUARY 2012" Linux "User Manuals"

.SH NAME
i3lock \- improved screen locker

.SH SYNOPSIS
.B i3lock
.RB [\|\-v\|]
.RB [\|\-n\|]
.RB [\|\-b\|]
.RB [\|\-i
.IR image.png \|]
.RB [\|\-c
.IR color \|]
.RB [\|\-t\|]
.RB [\|\-p
.IR pointer\|]
.RB [\|\-u\|]
.RB [\|\-e\|]
.RB [\|\-f\|]

.SH DESCRIPTION
.B i3lock
is a simple screen locker like slock. After starting it, you will see a white
screen (you can configure the color/an image). You can return to your screen by
entering your password.

.SH IMPROVEMENTS

.IP \[bu] 2
i3lock forks, so you can combine it with an alias to suspend to RAM (run "i3lock && echo mem > /sys/power/state" to get a locked screen after waking up your computer from suspend to RAM)
.IP \[bu]
You can specify either a background color or a PNG image which will be displayed while your screen is locked.
.IP \[bu]
You can specify whether i3lock should bell upon a wrong password.
.IP \[bu]
i3lock uses PAM and therefore is compatible with LDAP, etc.


.SH OPTIONS
.TP
.B \-v, \-\-version
Display the version of your
.B i3lock

.TP
.B \-n, \-\-nofork
Don't fork after starting.

.TP
.B \-b, \-\-beep
Enable beeping. Be sure to not do this when you are about to annoy other people,
like when opening your laptop in a boring lecture.

.TP
.B \-u, \-\-no-unlock-indicator
Disable the unlock indicator. i3lock will by default show an unlock indicator
after pressing keys. This will give feedback for every keypress and it will
show you the current PAM state (whether your password is currently being
verified or whether it is wrong).

.TP
.BI \-i\  path \fR,\ \fB\-\-image= path
Display the given PNG image instead of a blank screen.

.TP
.BI \-c\  rrggbb \fR,\ \fB\-\-color= rrggbb
Turn the screen into the given color instead of white. Color must be given in 3-byte
format: rrggbb (i.e. ff0000 is red).

.TP
.B \-t, \-\-tiling
If an image is specified (via \-i) it will display the image tiled all over the screen
(if it is a multi-monitor setup, the image is visible on all screens).

.TP
.BI \-p\  win|default \fR,\ \fB\-\-pointer= win|default
If you specify "default",
.B i3lock
does not hide your mouse pointer. If you specify "win",
.B i3lock
displays a hardcoded Windows-Pointer (thus enabling you to mess with your
friends by using a screenshot of a Windows desktop as a locking-screen).

.TP
.B \-e, \-\-ignore-empty-password
When an empty password is provided by the user, do not validate
it. Without this option, the empty password will be provided to PAM
and, if invalid, the user will have to wait a few seconds before
another try. This can be useful if the XF86ScreenSaver key is used to
put a laptop to sleep and bounce on resume or if you happen to wake up
your computer with the enter key.

.TP
.B \-f, \-\-show-failed-attempts
Show the number of failed attempts, if any.

.TP
.B \-\-debug
Enables debug logging.
Note, that this will log the password used for authentication to stdout.

.SH DPMS

The \-d (\-\-dpms) option was removed from i3lock in version 2.8. There were
plenty of use-cases that were not properly addressed, and plenty of bugs
surrounding that feature. While features are not normally removed from i3 and
its tools, we felt the need to make an exception in this case.

Users who wish to explicitly enable DPMS only when their screen is locked can
use a wrapper script around i3lock like the following:

.Vb 6
\&	#!/bin/sh
\&	revert() {
\&	  xset dpms 0 0 0
\&	}
\&	trap revert HUP INT TERM
\&	xset +dpms dpms 5 5 5
\&	i3lock -n
\&	revert
.Ve

The \-I (-\-inactivity-timeout=seconds) was removed because it only makes sense with DPMS.

.SH SEE ALSO
.IR xautolock(1)
\- use i3lock as your screen saver

.SH AUTHOR
Michael Stapelberg <michael+i3lock at stapelberg dot de>

Jan-Erik Rediger <badboy at archlinux.us>
